/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConsentRouteImport } from './routes/_authenticated/consent'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedStudentScreeningRouteImport } from './routes/_authenticated/student/screening'
import { Route as AuthenticatedStudentSupportRouteImport } from './routes/_authenticated/student/support'
import { Route as AuthenticatedStudentResultsSessionIdRouteImport } from './routes/_authenticated/student/results.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsentRoute = AuthenticatedConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentScreeningRoute =
  AuthenticatedStudentScreeningRouteImport.update({
    id: '/student/screening',
    path: '/student/screening',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSupportRoute =
  AuthenticatedStudentSupportRouteImport.update({
    id: '/student/support',
    path: '/student/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentResultsSessionIdRoute =
  AuthenticatedStudentResultsSessionIdRouteImport.update({
    id: '/student/results/$sessionId',
    path: '/student/results/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/screening': typeof AuthenticatedStudentScreeningRoute
  '/student/support': typeof AuthenticatedStudentSupportRoute
  '/student/results/$sessionId': typeof AuthenticatedStudentResultsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consent': typeof AuthenticatedConsentRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/screening': typeof AuthenticatedStudentScreeningRoute
  '/student/support': typeof AuthenticatedStudentSupportRoute
  '/student/results/$sessionId': typeof AuthenticatedStudentResultsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/consent': typeof AuthenticatedConsentRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/screening': typeof AuthenticatedStudentScreeningRoute
  '/_authenticated/student/support': typeof AuthenticatedStudentSupportRoute
  '/_authenticated/student/results/$sessionId': typeof AuthenticatedStudentResultsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/consent'
    | '/student/dashboard'
    | '/student/screening'
    | '/student/support'
    | '/student/results/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/consent'
    | '/student/dashboard'
    | '/student/screening'
    | '/student/support'
    | '/student/results/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/consent'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/screening'
    | '/_authenticated/student/support'
    | '/_authenticated/student/results/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/consent': {
      id: '/_authenticated/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthenticatedConsentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/screening': {
      id: '/_authenticated/student/screening'
      path: '/student/screening'
      fullPath: '/student/screening'
      preLoaderRoute: typeof AuthenticatedStudentScreeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/support': {
      id: '/_authenticated/student/support'
      path: '/student/support'
      fullPath: '/student/support'
      preLoaderRoute: typeof AuthenticatedStudentSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/results/$sessionId': {
      id: '/_authenticated/student/results/$sessionId'
      path: '/student/results/$sessionId'
      fullPath: '/student/results/$sessionId'
      preLoaderRoute: typeof AuthenticatedStudentResultsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsentRoute: typeof AuthenticatedConsentRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentScreeningRoute: typeof AuthenticatedStudentScreeningRoute
  AuthenticatedStudentSupportRoute: typeof AuthenticatedStudentSupportRoute
  AuthenticatedStudentResultsSessionIdRoute: typeof AuthenticatedStudentResultsSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsentRoute: AuthenticatedConsentRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentScreeningRoute: AuthenticatedStudentScreeningRoute,
  AuthenticatedStudentSupportRoute: AuthenticatedStudentSupportRoute,
  AuthenticatedStudentResultsSessionIdRoute:
    AuthenticatedStudentResultsSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
